# Generated by Django 5.0.3 on 2024-04-16 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maximum_eligible_days', models.PositiveIntegerField(verbose_name='Nombre maximum de jours éligibles')),
                ('accumulation_mode', models.CharField(choices=[('cumul', 'Cumul'), ('reset', 'Reset')], max_length=10, verbose_name="Mode d'accumulation des jours d'absences")),
                ('absence_day_use', models.CharField(max_length=100, verbose_name="Utilisation des jours d'absences")),
                ('negative_balance', models.BooleanField(verbose_name='Autorisation de solde négatif')),
                ('nombre_jours_reportes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de jours pouvant être reportés')),
                ('number_of_reported_days', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name="Date d'expiration des jours reportés (en mois)")),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_entree_vigueur', models.DateField(verbose_name="Date d'entrée en vigueur du contrat")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('periode_dessai', models.BooleanField(verbose_name="Période d'essai")),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mois_debut', models.CharField(choices=[('janvier', 'Janvier'), ('février', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('août', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('décembre', 'Décembre'), ('debut_contrat', 'Début du contrat')], max_length=20, verbose_name='Mois de début')),
                ('duree', models.IntegerField(choices=[(1, '1 mois'), (2, '2 mois'), (3, '3 mois'), (6, '6 mois'), (12, '12 mois')], verbose_name='Durée (en mois)')),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
            },
        ),
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=255, verbose_name='Intitulé de poste')),
                ('niveau', models.CharField(choices=[('Junior', 'Junior'), ('Moyen', 'Moyen'), ('Senior', 'Senior')], max_length=10, verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Emploi',
                'verbose_name_plural': 'Emplois',
            },
        ),
        migrations.CreateModel(
            name='EntiteJuridique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raison_sociale', models.CharField(max_length=255, verbose_name='Raison sociale (Nom)')),
                ('matricule', models.CharField(max_length=100, verbose_name='Matricule')),
                ('adresse_domiciliation', models.CharField(max_length=255, verbose_name='Adresse de Domiciliation')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(max_length=20, verbose_name='Code postal')),
                ('departement', models.CharField(max_length=100, verbose_name='Département')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Entité Juridique',
                'verbose_name_plural': 'Entités Juridiques',
            },
        ),
        migrations.CreateModel(
            name='HeuresContractuelles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heures_par_jour', models.PositiveIntegerField(verbose_name='Heures par jour')),
                ('lundi', models.BooleanField(default=True)),
                ('mardi', models.BooleanField(default=True)),
                ('mercredi', models.BooleanField(default=True)),
                ('jeudi', models.BooleanField(default=True)),
                ('vendredi', models.BooleanField(default=True)),
                ('samedi', models.BooleanField(default=False)),
                ('dimanche', models.BooleanField(default=False)),
                ('max_heures_par_semaine', models.PositiveIntegerField(verbose_name="Nombre maximum d'heures par semaine")),
                ('max_heures_par_an', models.PositiveIntegerField(verbose_name="Nombre maximum d'heures par an")),
            ],
            options={
                'verbose_name': 'Heures contractuelles',
                'verbose_name_plural': 'Heures contractuelles',
            },
        ),
        migrations.CreateModel(
            name='LieuTravail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.CharField(choices=[('OpenSpace', 'OpenSpace'), ('BureauPropre', 'Bureau Propre'), ('Itinerant', 'Itinérant'), ('Hybride', 'Hybride')], max_length=20, verbose_name='Type')),
                ('capacite', models.PositiveIntegerField(verbose_name='Capacité')),
            ],
            options={
                'verbose_name': 'Lieu de travail',
                'verbose_name_plural': 'Lieux de travail',
            },
        ),
        migrations.CreateModel(
            name='Seniority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seniority_required', models.IntegerField(help_text="Veuillez entrer l'ancienneté requise du collaborateur en mois (entre 1 et 60).", unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Ancienneté requise du collaborateur (en mois)')),
                ('extra_leave_days', models.IntegerField(default=0, help_text='Veuillez entrer le nombre de jours de congé supplémentaire.', verbose_name='Jours de congé supplémentaire')),
            ],
            options={
                'verbose_name': 'Ancienneté',
                'verbose_name_plural': 'Anciennetés',
            },
        ),
        migrations.CreateModel(
            name='TypeAbsence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('deduire_du_compteur', models.BooleanField(verbose_name='Déduire ce temps depuis le compteur')),
                ('absence_remuneree', models.BooleanField(verbose_name='Absences rémunérée')),
                ('date_fin_obligatoire', models.BooleanField(verbose_name='Date de fin obligatoire')),
                ('demander_absence', models.BooleanField(verbose_name="Permettre de demander ce type d'absences")),
                ('autoriser_pieces_jointes', models.BooleanField(verbose_name='Autoriser les pièces jointes')),
                ('pieces_jointes_obligatoires', models.BooleanField(verbose_name='Obliger les pièces jointes')),
                ('description_obligatoire', models.BooleanField(verbose_name='Description obligatoire')),
                ('approbation_automatique', models.BooleanField(verbose_name='Approbation Automatique')),
            ],
            options={
                'verbose_name': "Type d'absence",
                'verbose_name_plural': "Types d'absences",
            },
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('matricule', models.CharField(max_length=100, verbose_name='Matricule')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, verbose_name='Genre')),
                ('nationalite', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('numero_telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(max_length=20, verbose_name='Code postal')),
                ('departement', models.CharField(max_length=100, verbose_name='Département')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('contact_urgence_nom', models.CharField(max_length=100, verbose_name="Nom de la personne à contacter en cas d'urgence")),
                ('contact_urgence_telephone', models.CharField(max_length=20, verbose_name="Téléphone de la personne à contacter en cas d'urgence")),
                ('email_personnel', models.EmailField(max_length=254, verbose_name='Email Personnel')),
                ('email_professionnel', models.EmailField(max_length=254, verbose_name='Email Professionnel')),
                ('date_anciennete', models.DateField(verbose_name="Date d'ancienneté")),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpoman.collaborateur', verbose_name='Manager')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.contrat', verbose_name='Contrat')),
                ('emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.emploi', verbose_name='Emploi')),
                ('entite_juridique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.entitejuridique', verbose_name="Entité Juridique associée à l'employé")),
            ],
            options={
                'verbose_name': 'Collaborateur',
                'verbose_name_plural': 'Collaborateurs',
            },
        ),
        migrations.CreateModel(
            name='CompteurAbsences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('type_compteur', models.CharField(choices=[('solde_fixe', 'Solde fixe'), ('heures_supplementaires', 'Heures supplémentaires'), ('sur_base_heures_travaillees', 'Sur la base des heures travaillées')], max_length=50, verbose_name='Type de compteur')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.configuration', verbose_name='Configuration')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.cycle', verbose_name='Cycle')),
                ('types_absences_autorises', models.ManyToManyField(to='corpoman.typeabsence', verbose_name="Liste de types d'absences autorisés")),
            ],
            options={
                'verbose_name': "Compteur d'absences",
                'verbose_name_plural': "Compteurs d'absences",
            },
        ),
        migrations.AddField(
            model_name='contrat',
            name='emploi_concerne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.emploi', verbose_name='Emploi concerné'),
        ),
        migrations.AddField(
            model_name='emploi',
            name='entite_juridique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.entitejuridique', verbose_name='Entité Juridique'),
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.collaborateur', verbose_name='Manager/Responsable')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
            },
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='Equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.equipe', verbose_name='Équipe'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='heures_contractuelles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.heurescontractuelles', verbose_name='Heures contractuelles'),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='lieu_travail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.lieutravail', verbose_name='Lieu de travail'),
        ),
        migrations.CreateModel(
            name='PolitiqueAbsences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('compteur_absences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.compteurabsences', verbose_name="Compteur d'absences")),
            ],
            options={
                'verbose_name': "Politique d'absences",
                'verbose_name_plural': "Politiques d'absences",
            },
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='politique_conges',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.politiqueabsences', verbose_name='Politique de congés'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='seniority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.seniority', verbose_name="Période d'ancienneté"),
        ),
        migrations.CreateModel(
            name='DemandeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents_joints', verbose_name='Documents joints')),
                ('approbateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approbateur', to='corpoman.collaborateur', verbose_name='Approbateur')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.collaborateur', verbose_name='Employé')),
                ('type_absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpoman.typeabsence', verbose_name="Type d'absence")),
            ],
            options={
                'verbose_name': "Demande d'absence",
                'verbose_name_plural': "Demandes d'absence",
            },
        ),
    ]
