# Generated by Django 5.0.4 on 2024-04-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='objet',
            field=models.CharField(blank=True, max_length=100, verbose_name='Objet du contrat'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emploi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entitejuridique',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lieutravail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='politiqueabsences',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
