# Generated by Django 5.0.4 on 2024-04-20 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoman', '0002_contrat_objet_alter_contrat_id_alter_emploi_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='absence_day_use',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='number_of_reported_days',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name="Date d'expiration des jours reportés (en mois)"),
        ),
    ]
