# Generated by Django 5.0.3 on 2024-04-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpoman', '0002_collaborateur_avatar_collaborateur_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='user',
        ),
    ]
