# Generated by Django 5.0.4 on 2024-04-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoman', '0003_remove_configuration_absence_day_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='seniority',
        ),
        migrations.AddField(
            model_name='configuration',
            name='seniority',
            field=models.ManyToManyField(to='corpoman.seniority', verbose_name="Période d'ancienneté"),
        ),
    ]
