# Generated by Django 5.0.3 on 2024-04-20 18:34

import corpoman.utils
import corpoman.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoman', '0003_remove_collaborateur_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[corpoman.validators.validate_avatar]),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='matricule',
            field=models.CharField(default=corpoman.utils.generate_matricule, max_length=11, unique=True, verbose_name='Matricule'),
        ),
    ]
