# Generated by Django 5.0.4 on 2024-04-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoman', '0004_configuration_nom_alter_configuration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='seniority',
            field=models.ManyToManyField(blank=True, to='corpoman.seniority', verbose_name="Période d'ancienneté"),
        ),
        migrations.AlterField(
            model_name='typeabsence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
