# Generated by Django 5.0.4 on 2024-04-24 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoman', '0010_alter_collaborateur_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveCollaborateur',
            fields=[
                ('collaborateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpoman.collaborateur')),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archive Collaborateur',
                'verbose_name_plural': 'Archives Collaborateurs',
            },
            bases=('corpoman.collaborateur',),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordonnes', to='corpoman.collaborateur', verbose_name='Manager'),
        ),
    ]
