# Generated by Django 5.0.6 on 2024-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpoman', '0011_archivecollaborateur_alter_collaborateur_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeabsence',
            name='situation',
            field=models.CharField(choices=[('Approuved', 'Approuvée'), ('StandBy', 'En attente'), ('Refused', 'Refusé')], default='StandBy', max_length=20, verbose_name='Situation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandeabsence',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
